server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oilpurchase
    username: root
    password: ak@IND%1066
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  application:
    name: oilpurchase

